### ISSUE TITLE
多端口

### ISSUE THREAD

**Issue by csghostxx** [jackrun123/cfiptest#1]
有没有考虑以后升级支持多端口扫描

**Comment by csghostxx** [comment]
5.226.179.0/24,443,8443,2053,2083,2087,2096

**Comment by jackrun123** [comment]
暂时不打算支持多端口，一般扫一个端口就够了。你可以前面先用masscan扫描那些端口是开放的。

你也可以生成两行IP信息测试不同端口
5.226.179.0/24,443
5.226.179.0/24,2053
