### ISSUE TITLE
notls无法测速

### ISSUE THREAD

**Issue by qfsy** [jackrun123/cfiptest#2]
在命令行指定了-tls false 似乎没有作用，不会吧测速地址变成http，依然是https，我试过，不管是测速和测延迟都不行。

**Comment by jackrun123** [comment]
参数是 -tls=false，另外测速链接要使用worker部署，如果用page部署，会跳转到https的域名。测速链接不要带前面的http:// 或者 https://

不过我没测试过，我没测非tls的需求

**Comment by qfsy** [comment]
谢谢回复，测速地址是workers部署的，现在知道了是参数错了，没有加等号
